version: "3.9"
services:
  # Container do banco de dados
  rent_games_database:
    image: postgres
    container_name: rent-games-database
    restart: always
    ports:
      - 5432:5432 
    environment:
      - POSTGRES_USER=victor
      - POSTGRES_PASSWORD=nest123
      - POSTGRES_DB=dev      
    volumes:
      - pgdata:/data/postgres
      
volumes:
  pgdata:
    driver: local